# Generated by Django 4.1.3 on 2022-12-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createForm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatype',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
