# Generated by Django 4.1.3 on 2022-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createForm', '0002_rename_parent_id_datatype_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='slug',
            new_name='fa_name',
        ),
        migrations.AddField(
            model_name='attribute',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='max',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='max_length',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attribute',
            name='min_length',
            field=models.BooleanField(default=False),
        ),
    ]
