# Generated by Django 4.1.3 on 2022-12-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createForm', '0004_dataattribute_created_at_dataattribute_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataattribute',
            name='default',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='dataattribute',
            name='max',
            field=models.IntegerField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='dataattribute',
            name='max_length',
            field=models.IntegerField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='dataattribute',
            name='min',
            field=models.IntegerField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='dataattribute',
            name='min_length',
            field=models.IntegerField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='dataattribute',
            name='order',
            field=models.IntegerField(default=1, max_length=264),
        ),
    ]
