# Generated by Django 4.1.3 on 2022-12-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createForm', '0005_dataattribute_default_dataattribute_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataattribute',
            name='attribute',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='createForm.attribute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='dataType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataAttributes', to='createForm.datatype'),
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='max_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='min_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataattribute',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
