# Generated by Django 4.1.3 on 2022-12-11 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createForm', '0006_alter_dataattribute_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.AddField(
            model_name='datatype',
            name='limit_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='createForm.limitentry'),
        ),
    ]
