# Generated by Django 4.1.3 on 2022-12-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createForm', '0007_limitentry_datatype_limit_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createForm.datatype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datatype',
            name='user_entry',
            field=models.ManyToManyField(related_name='dataTypes', through='createForm.UserEntry', to=settings.AUTH_USER_MODEL),
        ),
    ]
