# Generated by Django 4.1.3 on 2022-12-13 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('createForm', '0008_userentry_datatype_user_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='user_entry',
            field=models.ManyToManyField(related_name='dataTypes_entry', through='createForm.UserEntry', to=settings.AUTH_USER_MODEL),
        ),
    ]
