# Generated by Django 4.1.3 on 2022-11-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('country_key', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('code', models.CharField(max_length=264, null=True)),
                ('short_code', models.CharField(max_length=264, null=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('code', models.CharField(max_length=264, null=True)),
                ('short_code', models.CharField(max_length=264, null=True)),
                ('status', models.BooleanField(default=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.country')),
            ],
        ),
        migrations.CreateModel(
            name='RuralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('code', models.CharField(max_length=264, null=True)),
                ('sector_id', models.CharField(max_length=264, null=True)),
                ('short_code', models.CharField(max_length=264, null=True)),
                ('status', models.BooleanField(default=1)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.county')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.province')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.province'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('code', models.CharField(max_length=264, null=True)),
                ('sector_id', models.CharField(max_length=264, null=True)),
                ('short_code', models.CharField(max_length=264, null=True)),
                ('status', models.BooleanField(default=1)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.county')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.province')),
            ],
        ),
    ]
