# Generated by Django 4.1.3 on 2022-12-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('createForm', '0008_userentry_datatype_user_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=264)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataAttribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createForm.dataattribute')),
                ('dataType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createForm.datatype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createForm.userentry')),
            ],
        ),
    ]
